modLoader="javafml"
loaderVersion="[${lang_version},)"
issueTrackerURL="https://github.com/TheCBProject/ChickenChunks"
license="The MIT License (MIT)"

[[mods]]
	modId="chickenchunks"
	displayName="ChickenChunks"
	version="${file.jarVersion}"

	updateJSONURL="https://version-check.covers1624.net/check/?mod=ChickenChunks&mc=${mc_version}"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/chicken-chunks-1-8"
	authors="ChickenBones, covers1624"
	description="Advanced ChunkLoading management"
[[dependencies.chickenchunks]]
	modId="forge"
	mandatory=true
	versionRange="[${forge_version},)"
	ordering="NONE"
	side="BOTH"
[[dependencies.chickenchunks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.chickenchunks]]
    modId="codechickenlib"
    mandatory=true
    versionRange="${ccl_version_range}"
    ordering="NONE"
    side="BOTH"
